

runtime:
  device: cpu


models:
  resnet18:
    path: models/resnet18/resnet18-5c106cde.pth
  face-parse-bisent:
    path: models/face-parse-bisent/79999_iter.pth
    num_classes: 19
  s3fd:
    path: models/s3fd/s3fd-619a316812.pth
  dwpose:
    path: models/dwpose/dw-ll_ucoco_384.onnx
  sd-vae-ft-mse:
    path: models/sd-vae-ft-mse/diffusion_pytorch_model.bin
  # wisper:
  #   path:
  # musetalk:


  # musetalk:
  #   version: v1.5
  #   root: models/musetalk-v1.5
  #   unet: models/musetalk-v1.5/unet.pth
  #   config: models/musetalk-v1.5/musetalk.json
  # whisper:
  #   root: models/whisper

